Implement amazing books
Rudy-Menekam/amazing-book pull request #1
Opened 2023-01-17 15:08 UTC by Rudy-Menekam

In this PR,
 - You can add and delete books

2023-01-17 16:06 UTC, codepantha requested changes
# STATUS: CHANGES REQUIRED ♻️ 

## Hi team 👋 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif"/>

## Highlights 🎯 
✔️ Descriptive PR
✔️ No linter errors
✔️ Used GitHub Flow correctly

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-17 16:06 UTC, codepantha commented on js/index.js
> +  console.log(books);
- [ ] Kindly remove all `console.log`s from your commited code as it makes your code look messy 👍

2023-01-17 16:06 UTC, codepantha commented on js/index.js
> +            </section>
- [ ] Clicking the "Add" button to add a book simply reloads the page and the book data is not persisted to `localstorage`. Please fix this functionality 🙏 
- [ ] Also, since the books are not saving correctly, they are also not being displayed at the top of the page as per requirements. Please fix this as well 🙏

2023-01-17 16:06 UTC, codepantha commented on js/index.js
> +}
- [ ] Regardless of the fact that your `onAddElement()` function is not currently working and therefore, I have been unable to test this function, it is quite obvious that you are manipulating the DOM to remove the book element without removing the actual book from the `books` array and the `localStorage`. Please factor this into your solution 👍

2023-01-19 08:15 UTC, Rustamxon7 approved these changes
Hi @Rudy-Menekam, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Developer-512px-10](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

## Highlights
1. No Linters errors 💯
2. All requirements are complete 💯

## Optional suggestions
No optional suggestions :)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 08:16 UTC, merged